// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghmrxgknancxndaxkili.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdobXJ4Z2tuYW5jeG5kYXhraWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDExOTgsImV4cCI6MjA2OTUxNzE5OH0.vVBGzC155bHv2QU0OqIva2G5JuxrU9CXtWuMpGVjtfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});